#!/bin/sh
while read file
do
	case "$1" in
	"d" )
		[ "$(printf "No\\nYes" | dmenu -i -p "Are you sure you want to delete $file?")" = "Yes" ] && mv "$file" ~/.trash && notify-send "$file deleted." ;;
	"r")
		convert -rotate 90 "$file" "$file" ;;
	"R")
		convert -rotate -90 "$file" "$file" ;;
	"w")
		setbg "$file" ;;

	"c")
		[ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs | awk '{print $2}' | dmenu -l 20 -i -p "Copy file(s) to where?" | sed "s|~|$HOME|g")"
		[ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
		cp "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file copied to $destdir." &
		;;
	esac
done
